name: ci

on:
  push:

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_API_KEY: ${{ secrets.API_KEY }}
  IBM_CLOUD_REGION: us-south
  REGISTRY_HOSTNAME: https://index.docker.io/v1/
  IMAGE_NAME: simplynd/nd-react
  DEPLOYMENT_NAME: react-test
  PORT: 80

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: simplynd/nd-react:latest
      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry

      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}"
          ibmcloud target -r us-south
          ibmcloud target -g Default
      
      # Create Registry Secret
      - name: Create Registry Secret
        run: |
          ibmcloud ce secret create --format registry --name privatedocker --server 'https://index.docker.io/v1/' --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      # Deploy to Code Engine
      - name: Deploy to Code Engine
        run: |
          ibmcloud ce app create --name myhelloapp --image "${REGISTRY_HOSTNAME}""${IMAGE_NAME}" --registry-secret privatedocker --port 80